### ISSUE TITLE
Cant seem to be caching, no logs to show if its caching

### ISSUE THREAD

**Issue by jeremyrajan** [patrixr/strapi-middleware-cache#12]
Hi,

First all! Thanks a lot for the lib. I have been looking for one and I hope the official strapi team starts looking at this 👍 .

I am trying to get it working on my project. I have set up the middleware and add the model.

```javascript
module.exports = ({ env }) => ({
  settings: {
    cache: {
      enabled: true,
      models: ['ratings']
    },
  },
});

```

I don't see the message.
![image](https://user-images.githubusercontent.com/2890683/88450381-19f7e180-ce81-11ea-91f4-180421354639.png)

Anything that I am doing wrong? Following is the debug info:
![image](https://user-images.githubusercontent.com/2890683/88450392-2ed47500-ce81-11ea-92c8-22c08ad3bb4c.png)

Please let me know if you need further info and grateful if you can help :)

Cheers,
Jeremy

**Comment by jeremyrajan** [comment]
My bad! 🤦 . I had called the file wrongly. It was supposed to `middleware.js`, I had it as `middlewares.js`. Fixed now. Thank you :)

**Comment by patrixr** [comment]
Glad to hear it's working ! Cheers :)
