### ISSUE TITLE
Does this work for GraphQL queries as well?

### ISSUE THREAD

**Issue by RanaOsamaAsif** [patrixr/strapi-middleware-cache#14]
I have Strapi setup and in my frontend all the interaction with Strapi happens via GraphQL. When using this middleware will caching work?

**Comment by patrixr** [comment]
Hi @RanaOsamaAsif 

As of now only the standard rest endpoints can be cached with this middleware. So gql requests would not

**Comment by RanaOsamaAsif** [comment]
@patrixr thanks a lot for the clarification. 

There is one more thing I want to know, does strapi provides any sort of caching out of box? Or it can only be added using middleware modules?

**Comment by patrixr** [comment]
@RanaOsamaAsif Not that I know of. I built this middleware because I could not find anything in Strapi for it. Do let me know if you find out :)

**Comment by derrickmehaffy** [comment]
For clarification, Strapi does not have any built in caching mechanism, and to my knowledge this community middleware is the only one I'm aware of.

**Comment by liyaodong** [comment]
Would be great if this plugin can support graphql cache. but anyway, thanks for all the contributers.
