### ISSUE TITLE
Manage Redis disconnections and re-connections

### ISSUE THREAD

**Issue by sgarcia-g** [patrixr/strapi-middleware-cache#15]
Hello :wave: 

We are using the library and so far is working great, but we came up with a possible scenario: If the connection with Redis is lost for whatever reason (maybe the cache goes down, or the connection pipe gets broken), then the library will try to fetch data from Redis and will get stuck forever (which is far from ideal). It would be great if the library could handle this case.

We think that this could be avoided by doing two things:

1. Change the status flag to use the `status` property of the ioredis' client.
2. Including a cache timeout, just in case.

We have some work in progress in a fork, so I will open a draft PR, but I would like to hear your thoughts on this one.

Keep up the good work with the library! :D

**Comment by patrixr** [comment]
Hi @sgarcia-g 

Thanks for this !

I've been meaning to improve overall safety and error management for a while :)
I'll take a look at the pull request 🥳
