### ISSUE TITLE
Changes to bust function introduced in v1.0.9 break admin cache busting

### ISSUE THREAD

**Issue by julesrenaud** [patrixr/strapi-middleware-cache#19]
When editing a collection type in the admin cache busting isn't working anymore because the `pattern` variable in the `bust` function isn't using `pluralize` since v1.0.9, which makes it so that the pattern isn't matching the cache keys anymore. Everything works fine for single types though, since the pluralize function is avoided in this context (as it should).

v1.0.8:
```js
const pattern     = new RegExp(`^/${pluralize(model)}`);
```

v1.0.9
```js
const pattern     = new RegExp(`^/${model}`);
```

Using a bit of your code from function bustAdmin, I'm able for figure out if the pattern should be pluralized or not (This works for both single types and collection types):

```js
const bust = (model) => async (ctx, next) => {
  const modelCfg = _.find(toCache, (cfg) => {
    return cfg.model === (cfg.singleType ? model : pluralize(model));
  });

  const pattern     = new RegExp(`^/${modelCfg.model}`);
  const keys        = await cache.keys() || [];

  await next();

  if (!_.inRange(ctx.status, 200, 300)) return;

  await Promise.all(
    _.filter(keys, k => pattern.test(k))
      .map(k => cache.del(k))
  );
}
```

**Comment by patrixr** [comment]
Hi @julesrenaud 

Thanks for catching this ! Looks like my test cases were insufficient. I'm making a fix for this now.

It has been working thus far because matching the `/post/` regex to the plural `"posts"` works, but that stops being true for a term like `/academy/` and `"academies"`

I'm adding a fix for this now

**Comment by patrixr** [comment]
@julesrenaud 

version [1.0.10](https://www.npmjs.com/package/strapi-middleware-cache) is now on npm. Admin cache bust should be working as expected.

Let me know if there's any issues

**Comment by julesrenaud** [comment]
> It has been working thus far because matching the `/post/` regex to the plural `"posts"` works, but that stops being true for a term like `/academy/` and `"academies"`

Yes, I forgot to mention that the endpoint for which cache wasn't busting had that condition (gallery -> galleries). Thanks a lot for the fix!
