### ISSUE TITLE
Modify settings to support custom object

### ISSUE THREAD

**Issue by derrickmehaffy** [patrixr/strapi-middleware-cache#2]
So in looking at your code, it would appear you are specifically pulling out config options that may not always apply.

Looking through the ioredis config options (and what I am currently testing) is what is known as the Redis HA config or Sentinel system: https://github.com/luin/ioredis#sentinel

While it's a tad difficult to see in this example screenshot:

![image](https://user-images.githubusercontent.com/8593673/82182687-7d6dfd80-9899-11ea-9814-407b0146dc59.png)

Basically there are 3 servers, running 6 services:

Server 1: Redis Server + Sentinel (Master)
Server 2: Redis Server + Sentinel (Slave)
Server 3: Redis Server + Sentinel (Slave)

When configuring the ioredis for the cache, we would simply pass the Sentinel addresses like:

```js
var redis = new Redis({
  sentinels: [
    { host: "192.168.10.41", port: 26379 },
    { host: "192.168.10.42", port: 26379 },
    { host: "192.168.10.43", port: 26379 },
  ],
  name: "redis-primary",
});
```

And thus there would be no root `host, port, pass, ect` and would be contained within the sentinels array. Likewise for the name as sentinels can manage multiple Redis "clusters" (tad confusing here I know)

I will play around locally and see if I can find a solution to submit a PR unless you already have some ideas. Personally I think just simply having a config option for `redisConfig: {}` to allow someone to use whatever they want would be better then having the config options in the root of the settings object.

FYI I am also testing on the latest Strapi `next` tagged release which is what will be `3.0.0-rc.1` when they release it (Release Candidate for the Stable)

**Comment by derrickmehaffy** [comment]
Example would be something similar to this 

```json
{
	"cache": {
		"enabled": true,
		"type": "redis",
		"redisConfig": {
			"sentinels": [
				{ "host": "192.168.10.41", "port": 26379 },
				{ "host": "192.168.10.42", "port": 26379 },
				{ "host": "192.168.10.43", "port": 26379 }
			],
			"name": "redis-primary"
		},
		"max": 500,
		"maxAge": 3600000
	}
}
```

**Comment by patrixr** [comment]
@derrickmehaffy That sounds perfectly reasonable to me, I'll add this in. 

I haven't dealt with redis clusters so it's preferable for me to match your requirements. very helpful !

**Comment by derrickmehaffy** [comment]
The clusters themselves I think will be more complicated, but Sentinels are fairly simple here. I'm working on a PR right now

**Comment by derrickmehaffy** [comment]
Going to close this out as it was "fixed" in https://github.com/patrixr/strapi-middleware-cache/commit/325cffbf3f587282442912423c1ebef81b630772

Will open a new issue to discuss clusters
