### ISSUE TITLE
Redis connection failing when using this middleware to connect to redis server running on DEV/UAT

### ISSUE THREAD

**Issue by vinod77** [patrixr/strapi-middleware-cache#21]
**Description:** Redis connection failing when using a separate `redis` server

This middleware working fine on local with running local `redis` server.

But I have a separate `redis` instance running on DEV/UAT/PROD and i connect to it through a different library (not ioredis)

I have used this below configuration:
// config/middleware.js
```
module.exports = ({ env }) => ({
  settings: {
    cache: {
      enabled: true,
      type: 'redis',
      maxAge: 3600000,
      models: [
        {
          model: 'listings',
          maxAge: 1000000,
        }
      ]
    }
  }
});
```

My DEV/UAT/PROD `redis` has a different type: redis-something.

How can i make this middleware work with a different redis server?

**Comment by derrickmehaffy** [comment]
@vinod77 what package are you trying to use to connect to the Redis server? I had suggested to @patrixr earlier on in the development to use ioredis simply because it has the widest support especially when it comes to sentinel clusters.

**Comment by vinod77** [comment]
Hi @derrickmehaffy 
We are using our own library written on top of `koa-redis` & `ioredis` to connect to our `redis` server on DEV/UAT/PROD and it requires different set/type of properties to connect to it (not just `host` & `port`).

When we use these set of properties in the `middleware.js`.. `strapi-middleware-cache` & `ioredis` is not able to understand those attributes. So this middleware is failing to connect to our own `redis` server running on DEV/UAT/PROD.

**Note:** This middleware is working as expected on my local, connecting to `redis` running on local with `host` & `port`.
Thanks!

**Comment by derrickmehaffy** [comment]
Since the `./config/middleware.js` is just a JS file you could probably have it pull the information from your own koa-redis but it will need to be passed in the ioredis format :thinking: 

In the case of this package, the `redisConfig` object is just directly handed off to ioredis so if your other package is using a similar format there shouldn't be any issue but it will need to be expressly defined in the middleware settings.

When I was assisting @patrixr with determining the correct way to handle it, it was suggested to handle it at the middleware level until we (the Strapi team) and properly re-implement redis within the core project and using the database.js (for things like session storage, ect).

The other alternative for you would be to fork this package and customize it to fit your use-case.

**Comment by vinod77** [comment]
Hi @derrickmehaffy 
You are super responsive to all Strapi users. Thanks for your responses.. :)

Actually the format we use is not the same to connect to our DEV/UAT `redis`.
As you said, we can consider with other alternative, forking this package and customizing it fit to our use-case.
Thank you!

**Comment by derrickmehaffy** [comment]
No problem!

**Comment by patrixr** [comment]
Sorry to hear it's not working

One idea could be to make the store fully customisable, allowing users to create their own.
Changes would be:
- Replace the "type" prop name to "store"
- Support both strings and custom stores as params

e.g

```javascript
module.exports = ({ env }) => ({
  settings: {
    cache: {
      enabled: true,
      store: 'redis',  // Uses the default redis store
      maxAge: 3600000,
      models: [
        {
          model: 'listings',
          maxAge: 1000000,
        }
      ]
    }
  }
});


// OR

module.exports = ({ env }) => ({
  settings: {
    cache: {
      enabled: true,
      store: require('../../my_store'),  // Uses the user's own store
      maxAge: 3600000,
      models: [
        {
          model: 'listings',
          maxAge: 1000000,
        }
      ]
    }
  }
});
```

As long as users follow the store's predefined structure things should work.

Thoughts ? @derrickmehaffy  @vinod77

**Comment by derrickmehaffy** [comment]
I think for the moment @patrixr we should hold off making any major config changes as I still need to poke our backend engineers about future native Redis support within Strapi (for various plugins to connect to the same database and define the database in our database.js)

**Comment by derrickmehaffy** [comment]
There are a handful of other middlewares that will eventually need to have an option for Redis such as:

- Client session storage 
- Rate limit logging information
- GraphQL subscriptions
- Various community packages (such as this one :wink: )

**Comment by patrixr** [comment]
Sounds good ! Very happy to rework this module whenever a native redis integration comes into Strapi 😄 
(possibly a Strapi cache _a la_ rails ?)

I'll close this ticket and we can revisit this later on.
