### ISSUE TITLE
Cache not evicted when publishing or unpublishing

### ISSUE THREAD

**Issue by abarmp** [patrixr/strapi-middleware-cache#22]
Reproduction Steps:

1) Create a new item e.g. a new page under pages
2) Get the list of pages e.g. /pages, the new unpublished item is missing as expected
3) Publish the new page
4) Get the list of pages /pages, the newly published item is missing

The same is true when changing state from published to unpublished. The cache is not evicted and as a result the item is still visible in the list eventhough it is not published

The workaround for this issue is to publish and then modify in order to evict the cache

**Comment by derrickmehaffy** [comment]
Can confirm, it's likely related to the new APIs for the Draft and Publish feature.

**Comment by patrixr** [comment]
@abarmp @derrickmehaffy 

I've added support for the new publish feature. Cache should show be busted when a record is published on unpublished.

Try it out in the latest version, and let me know if there are any issues @abarmp  :)

Fixed by #23

**Comment by abarmp** [comment]
@patrixr Looks ok thank you very much for the quick reaction!! Great work!!
