### ISSUE TITLE
How I can manually bust the cache for a specific model? 

### ISSUE THREAD

**Issue by a1tem** [patrixr/strapi-middleware-cache#24]
Hi, is it possible to bust the cache for a specific model by using id?

I need some instructions on how I can do it inside of my controller.

Thanks!

**Comment by patrixr** [comment]
Hi @a1tem 

This middleware wasn't really designed to be used that way, it acts more as a shell over the api.
However, until I figure out a proper way to deal with this, here is an (untested) **_hack_** you can try

```javascript
// your controller file

const { cache } = require('strapi-middleware-cache');

// when needed
module.exports = {
  yourControllerMethod: async () => {
    const keys = await cache.keys();
    await Promise.all(
          _.filter(keys, k =>/^yourmodelname/.test(k)).map(k => cache.del(k))
     );
  }
}
```

Notes:
- I don't recommend using this, this is a direct access to the underlying cache
- you have to bust the cache for collections of that model as well, as that specific ID might be included in them

**Comment by a1tem** [comment]
@patrixr Thank you very much, I will try this approach and let you know. It would be great if you add a method to your module that we can call from the controllers/services/ etc... to deal with this type of situation.

**Comment by a1tem** [comment]
@patrixr any ideas?

**Comment by a1tem** [comment]
For everyone who might be interested in this, I have temporally solved this using redis:
```js
    const Redis = require("ioredis");    
    const redis = new Redis({
      port: 6379, 
      host: "127.0.0.1",
    });

    const pipeline = redis.pipeline();
    pipeline.del(
      `LRU-CACHE!-k-strapi-middleware-cache:/products/slug/${product.slug}`
    );
    pipeline.exec();

```

**Comment by derrickmehaffy** [comment]
(You should be able to import the redis settings from the middleware, something like `strapi.config.middleware.settings.cache.redisConfig` )

**Comment by patrixr** [comment]
@a1tem I've just updated the middleware to include an entry point to the cache in the Koa context (needs to be explicitly enabled)

Hopefully it can help with your issues

**Comment by a1tem** [comment]
@patrixr perfect! Thank you very much!
