### ISSUE TITLE
Bust cache from Models - Lifecycle hooks

### ISSUE THREAD

**Issue by jainsuneet** [patrixr/strapi-middleware-cache#27]
I have a custom API which get's the data from different content types. The inbuilt mechanism doesn't automatically refreshes the cache on custom routes if the content type data is changed. As per documents `ctx` is required to bust the cache.

`await ctx.middleware.cache.bust({ model: 'posts' });`

But `ctx` is not available in models. How can I manually bust the cache from models life cycle hooks like beforeDelete

**Comment by andreciornavei** [comment]
Hello @jainsuneet, same issue here... 
This issue lives in this piece of code https://github.com/patrixr/strapi-middleware-cache/blob/master/lib/index.js#L97-L107
Maybe a better approach is inject the cache object into strapi entire scope instead only ctx like below.
To not broke the script logical changing the existent code, I just added the second line that inject `clearCache` and `cache` into strapi scope.

```js
if (withKoaContext) {
   strapi.cache = { bust: clearCache, store:  cache }
   strapi.app.use((ctx, next) => {
     _.set(ctx, 'middleware.cache', {
       bust:   clearCache,
       store:  cache
     })
     return next();
   });
}
```

Could it become a valid PR?

**Comment by patrixr** [comment]
@jainsuneet @andreciornavei 

Sorry for the late reply.

I think the snippet of code above could definitely be a valid PR. However I wouldn't want to step on the toes of the Strapi developers by populating (potentially overwriting) `strapi.cache`.

Maybe `strapi.middleware.cache` would be more appropriate ?

**Comment by andreciornavei** [comment]
@patrixr of course, let's proceed by this way. I'll send a PR soon.
Also, I'm implementing severe changes on your project to serve my purposes. Should you like to discuss that after?

**Comment by patrixr** [comment]
@andreciornavei Sounds good !

As long as the changes are generic and serve a general purpose for others I'm happy to consider them 👍
