### ISSUE TITLE
How to connect to RedisLabs

### ISSUE THREAD

**Issue by insivika** [patrixr/strapi-middleware-cache#29]
Hello, thank you kindly for putting together this package. I'm very new to redis and I'm having a hard time connect to the redis instance I set up on Redislabs 

My `/config/middleware.js` files looks like this (some values have been changed): 

```
  settings: {
    cache: {
      enabled: true,
      type: 'redis',
      maxAge: 3600000,
      models: ['posts'],
      redisConfig: {
        url: 'redis://redis-5555.c8.us-east-1-4.ec2.cloud.redislabs.com:5555',
        name: 'content',
        password: 'secret_password',
      },
    },
  },
});
```

But I keep getting the following error:
```
Error: connect ECONNREFUSED 127.0.0.1:6379 at TCPConnectWrap.afterConnect [as oncomplete]
```

**Comment by patrixr** [comment]
Hi @insivika 

The `redisConfig` object is passed on directly to [ioredis](https://www.npmjs.com/package/ioredis), so you'll probably find better support on that github repo.

**Comment by insivika** [comment]
Hey @patrixr i actually figured it out🎉. In order to connect to redislabs you will need `host`, `port` and `password`. So using my example above the `redisConfig` object would look like:
```
 redisConfig: {
        host: 'redis-5555.c8.us-east-1-4.ec2.cloud.redislabs.com',
        port: 5555,
        password: 'secret_password',
      },
```

Hope this helps someone in the future...

**Comment by patrixr** [comment]
Hi @insivika, that's great ! Thank you for sharing : )
