### ISSUE TITLE
Cache not busted from admin anymore

### ISSUE THREAD

**Issue by roelbeerens** [patrixr/strapi-middleware-cache#32]
Hi,

With the latest version of Strapi (3.4.1) I noticed the cache isn't busted anymore when saving/updating an entry in the CMS.
I did notice in the source (https://github.com/patrixr/strapi-middleware-cache/blob/master/lib/index.js#L189) that the admin REST endpoint refer to `/content-manager/explorer/:scope` and that Strapi uses `/content-manager/collection-types/:scope`. 

I'm not fully sure if these routes have changed in the latest version of Strapi, but I think this prevents the busting of the cache as those do not match anymore.

**Comment by patrixr** [comment]
@roelbeerens Thank you for finding the fix, I've released version `1.4.1` to NPM with that included
