### ISSUE TITLE
Add option to bypass serving cache

### ISSUE THREAD

**Issue by julesrenaud** [patrixr/strapi-middleware-cache#34]
Hi!

I was wondering if you would consider adding an option to bypass serving the cache entry when matched in the cache store. I'm working on implementing  front-end cache using the ETag and If-None-Match headers. I've already added that layer to Strapi and in addition I'd like to leverage the cache store from this middleware by using the cache entry to create the ETag instead of querying the database every time.

**Comment by patrixr** [comment]
Hi @julesrenaud, I've written to you on #35.

I don't think this change can make it into the middleware in its current state. However if you wish to revisit it into a more fully-fledge feature I'm definitely open to it (which benefits many and doesn't require additional code to make sense)

Thanks for trying out the middleware, let me know if I can help : )
