### ISSUE TITLE
Support Redis Clusters (Distributed/Partitioned)

### ISSUE THREAD

**Issue by derrickmehaffy** [patrixr/strapi-middleware-cache#4]
So in my research and initial testing with clusters: https://github.com/patrixr/strapi-middleware-cache/pull/3

There seems to be an issue with `redis-lru` in which clusters are failing to set cache values due to how that package handles keys and pipelines. I'm currently looking at alternatives but we could try to reach out the package author about it.

I did see the following issue (from 2018) that seems slightly related: https://github.com/facundoolano/redis-lru/issues/11

**Comment by derrickmehaffy** [comment]
Possible option would be: https://github.com/havsar/node-ts-cache

**Comment by patrixr** [comment]
Good catch, I've been thinking about moving the LRU strategy up one level, so that it would be shared across all "storage engines"

**Comment by derrickmehaffy** [comment]
Indeed in the above package it does support file based cache although not sure how well that will work with Strapi and it does also have some additional strategy options. I'm sure there are other alternative packages out there, I'm not widely familiar with LRU based caching myself, so learning/researching as I go.

**Comment by derrickmehaffy** [comment]
I had started on a PR for this a while back: https://github.com/patrixr/strapi-middleware-cache/pull/3 but I am unable to finish it due to time.

If anyone else wants to take another stab at it please feel free.

**Comment by rafialikhan** [comment]
Is there any fix for this? redis cluster is giving Request time out.

**Comment by derrickmehaffy** [comment]
This is something that will probably be fixed in the new package for v4 as we changed the libs we use to build the cache keys and I plan to do some testing on the new package with a cluster.

https://github.com/strapi-community/strapi-plugin-rest-cache
The new provider package is using my [strapi-plugin-redis](https://github.com/strapi-community/strapi-plugin-redis) which is where the cluster will be built from.

I'm gonna close this for now as it won't be fixed in v3
