### ISSUE TITLE
Failing Redis connectivity when using DEV Redis

### ISSUE THREAD

**Issue by vinod77** [patrixr/strapi-middleware-cache#50]
**Description:** Failing Redis connectivity when using DEV Redis

**Steps to reproduce:**
1. Install this Library on the Strapi app
2. To connect this library to Redis - Use `Per-Model configuration` mentioned on `strapi-middleware-cache` NPM docs
2. Try to connect Strapi app to any DEV instance of Redis server (stop your local Redis server on your machine)
3.  Run the app
4. Throws below error: 
```
error [Cache] Redis connection failed
[2021-05-14T16:38:20.740Z] error Error: connect ECONNREFUSED 127.0.0.1:6379
```
So though my Strapi app is connected to DEV Redis but this middleware is still trying to connect to local Redis (127.0.0.1:6379) by default and since my local Redis is stopped, it throws above connectivity error.

We are using below Per-Model Configuration mentioned on https://www.npmjs.com/package/strapi-middleware-cache

```
module.exports = ({ env }) => ({
  settings: {
    cache: {
      enabled: true,
      type: 'redis',
      maxAge: 3600000,
      models: [
          'cars',
          'articles',
          'test',
          'trucks'
        ]
    }
  }
});
```
**Notes:** This middleware is working fine when Strapi app is connected to local Redis server. Issue is only when Strapi app is connected to DEV Redis

**Expected Behavior:** This middleware should work fine though we use `Local/DEV/UAT/PROD` Redis server's
Please let us know what configuration we need to pass to this middleware to use the correct Redis what Strapi is connected to?

**Comment by patrixr** [comment]
Hi @vinod77 

According to the config you posted, you haven't specified in a redis config, it therefore defaults to localhost.

You can pass in a `redisConfig` object as mentioned [here](https://github.com/patrixr/strapi-middleware-cache#configure-the-storage-engine), which is actually an [ioredis](https://github.com/luin/ioredis) config object

**Comment by vinod77** [comment]
It worked with above change. 
Thanks @patrixr
