### ISSUE TITLE
Key collision when using the same database across installs

### ISSUE THREAD

**Issue by selfagency** [patrixr/strapi-middleware-cache#51]
I am running half-a-dozen Strapi apps off a DigitalOcean droplet with Redis locally installed for caching purposes. I noticed today that two of those sites were showing each other's Strapi data in their front-end client applications. I quickly narrowed this down to an issue with key collisions in Redis. I was able to resolve the issue by using the `redisConfig` option to specify a `db` for each Strapi app. But I thought I would call it to your attention anyway in case this was an issue you were not aware of and might have an idea of how to resolve without needing to manually specify a different Redis database for each application. Thanks!

**Comment by derrickmehaffy** [comment]
For data security purposes I would suggest using a different DB regardless, and manually defining it.

**Comment by stafyniaksacha** [comment]
Hello @selfagency !
We can simply add a prefix setting for the key generated here https://github.com/patrixr/strapi-middleware-cache/blob/beta/lib/index.js#L32

I think it will simply solve the issue
