### ISSUE TITLE
Is it possible to set maxAge forever?

### ISSUE THREAD

**Issue by tianshanghong** [patrixr/strapi-middleware-cache#52]
I have a MongoDB server holding data which I don't change much. Most queries are to read. Is it possible to set maxAge for lru cache forever, thus the lru cache will never expire by itself?

**Comment by stafyniaksacha** [comment]
Hello @tianshanghong !
Yes you can, take a look at the beta branch and the per-model configuration here https://github.com/patrixr/strapi-middleware-cache/tree/beta#per-model-configuration
