### ISSUE TITLE
beta custom path cache issue

### ISSUE THREAD

**Issue by logicminds** [patrixr/strapi-middleware-cache#60]
I am testing out the beta branch as I have a custom route that is currently being cached forever despite updates.

## Use case
My courses/:id/children route computes the children of the current course (id).  So it is dependent of any course that are children of this item.  

## Issue
This custom children route only has GET implemented.  So the cache is never cleared despite the underlying children that have been updated.

## What I need
I want to bust the cache of the children route upon any of the courses are updated/deleted/posted.  In essence I want to just clear all children cache anytime any course is changed.  I don't need fine grain control.

## Alternatives
Looking at the beta docs, it seems I might be able to call the cache object directly within the model hooks.  This seems reasonable.  Why is the warning about using this feature there?

https://github.com/patrixr/strapi-middleware-cache/tree/beta#strapi-middleware

**Comment by patrixr** [comment]
Hi @logicminds 

You can bust the cache manually yourself whenever a course is updated/deleted/posted using the [Cache API](https://github.com/patrixr/strapi-middleware-cache/tree/beta#cache-api)

## Options:

- Add `withKoaContext: true` to the config, this will expose the cache api in the Koa context, which you can access through `ctx.middleware.cache`

- Add `withStrapiMiddleware: true` to the config, this will add the cache api to the strapi object, which you can access through `strapi.middleware.cache` (useful to bust the cache in lifecycle hooks)

Hope this helps

**Comment by logicminds** [comment]
I actually just used the 1.5.0 version.  I noticed the beta branch was not needed as those items above were added.

I ended up doing this in my course-items model.  Worked perfect.  Thanks for this project.

```javascript
async afterUpdate() {
      // bust all items cache, a better way would be to bust only the related items using the id
      await strapi.middleware.cache.bust({ model: 'course-items' });
    },
    async afterDelete() {
      await strapi.middleware.cache.bust({ model: 'course-items' });
    },
```
