### ISSUE TITLE
Cacheconf doesn't match with config

### ISSUE THREAD

**Issue by joacimastrom** [patrixr/strapi-middleware-cache#66]
The config I've setup in `config/middleware.js` does not match the config returned by `getCacheConfig` 

I have this model setup in my config: 
```
{
  model: "contracts",
  hitpass: false,
  injectDefaultRoutes: false,
  routes: [
    {
      path: "/contracts/:contractType/:countryLocale",
      method: "GET",
      paramNames: ["contractType", "countryLocale"],
    },
  ],
}
```

Calling `getCacheConfig("contracts")` returns the following, notice how the paramNames does not match
```
{
  singleType: false,
  hitpass: false,
  injectDefaultRoutes: false,
  headers: [],
  maxAge: 3600000,
  model: 'contracts',
  routes: [
    {
      path: '/contracts/:contractType/:countryLocale',
      method: 'GET',
      paramNames: [ 'contractType' ]
    }
}
```

**Comment by patrixr** [comment]
Hi,

After looking at the code base, it would appear `paramNames` is not a configurable parameter, so adding it yourself to the configuration would not take effect.

That said, there is an issue in the regex parsing, for which I've opened a PR, will merge it soon.

@stafyniaksacha did I miss anything here ?
