### ISSUE TITLE
Plans for Strapi v4

### ISSUE THREAD

**Issue by creazy231** [patrixr/strapi-middleware-cache#68]
Are there any plans for v4 since Strapi v4 is in beta currently?

**Comment by shihanjun19** [comment]
Under v4 version, I hope this middleware can be used

**Comment by talabatyMomin** [comment]
Any update on this thread? Would be great if there is some light at the end of the tunnel for v4.

**Comment by stafyniaksacha** [comment]
Yep, I'm working on the https://github.com/patrixr/strapi-middleware-cache/tree/feature/strapi-v4

A lot of new things are coming (authenticated cache, cache providers, admin controllers, plugin services, admin interface to clear caches, etc)

I'm currently writing the documentation for it, it quite close to be ended !

Feel free to join us on the Strapi official discord 
https://discord.gg/SDaM5eDm

**Comment by patrixr** [comment]
Thanks for all the work !

Apologies all, I haven't been able to keep up with v4 since my current work pulled me away from strapi. Luckily @stafyniaksacha picked up all the things I should have 🔥

**Comment by stafyniaksacha** [comment]
> Thanks for all the work !
> 
> Apologies all, I haven't been able to keep up with v4 since my current work pulled me away from strapi. Luckily @stafyniaksacha picked up all the things I should have 🔥

Can we meet on discord ? I got some questions about npm ;)

**Comment by Tragio** [comment]
@stafyniaksacha amazing work, thank you for picking it up and starting working on it. I'll try today in my v4 setup 😁 @patrixr thank you for the initial work and for putting all together for the community 💪

**Comment by patrixr** [comment]
> > Thanks for all the work !
> > 
> > Apologies all, I haven't been able to keep up with v4 since my current work pulled me away from strapi. Luckily @stafyniaksacha picked up all the things I should have 🔥
> 
> Can we meet on discord ? I got some questions about npm ;)

Sure thing, I'll be online today

**Comment by stafyniaksacha** [comment]
The plugin has moved here: https://github.com/strapi-community/strapi-plugin-rest-cache
