### ISSUE TITLE
same key used when using _where query param

### ISSUE THREAD

**Issue by th3m7J0** [patrixr/strapi-middleware-cache#75]
**Environment:** 
- node: v16.13.0
- npm: 7.17.0
- storage engine: redis

Hi, I'am having a request from the front with `_where` query param but in the cache its stored like object and all the `_where` requests will be the same.

When I have investigated the redis instance found in key `_where[object Object]`
I guess you are missing `toString()` to evaluate the `_where` object otherwise all the requests that uses `_where` will be the same for different objects.

**Comment by patrixr** [comment]
Interesting, I would assume query params are all strings, unless something kicks in beforehand to parse them.

The cache key code is located here: [generateCacheKey](https://github.com/patrixr/strapi-middleware-cache/blob/master/lib/utils/generateCacheKey.js). Perhaps we'd need to run `encodeURIComponent(JSON.stringify(param))` on each value ?

cc @stafyniaksacha

**Comment by danielehrhardt** [comment]
I have the same Problem.

**Comment by th3m7J0** [comment]
Hi @patrixr, yes a fix like that would be awesome
```.map((k) => `${k}=${encodeURIComponent(JSON.stringify(ctx.query[k])}`)```
can you please confirm the issue, and update the package ?

**Comment by th3m7J0** [comment]
any updates ?

**Comment by nao360** [comment]
Unfortunately same here; after an initial query of one or more `_where` parameters, all subsequent queries with `_where` parameters returns the same response for the given route. For now I have disabled caching on affected routes. A resolution for this issue would be much appreciated.

**Comment by patrixr** [comment]
Hey all, I'll try to get a fix in soon. I'm no longer very active on the project thus the delays

**Comment by rubms** [comment]
I have the same issue. I created a PR that fixes the issue: https://github.com/patrixr/strapi-middleware-cache/pull/79

It generates nice cache keys for _where query parameters likes: `LRU-CACHE!-k-strapi-middleware-cache:/model?_where={\"_or\":[{\"param1\":\"A\"},{\"param2\":\"B\"}]}&`
