### ISSUE TITLE
Support Admin Panel

### ISSUE THREAD

**Issue by kodermax** [patrixr/strapi-middleware-cache#8]
The cache is not cleared when we change data through the admin panel

**Comment by patrixr** [comment]
That's a known issue, the reason for that is because the admin panel does not use the standard REST endpoints to post data, so the cache is not busted. We can probably add that

**Comment by patrixr** [comment]
@kodermax The latest version (`1.0.6`) should take care of this. Have a try, let me know if there's any issues

**Comment by kieronbos** [comment]
Seems to be working for me now if I rename items & click save, they are reflected on the front end immediately.

Thanks

**Comment by kodermax** [comment]
@patrixr Great Work! Thanks!
