### ISSUE TITLE
strapi 4?

### ISSUE THREAD

**Issue by SVronskiy** [patrixr/strapi-middleware-cache#80]
Hello!

Is strapi cache compatible with strapi 4?

**Comment by ankur-arch** [comment]
I believe it isn't as of yet. 
Because the requirements state ```strapi 3.4.0```

![image](https://user-images.githubusercontent.com/64993082/147448234-5473e26f-b8ef-466c-aaaf-aba7e939320d.png)

**Comment by SVronskiy** [comment]
Ok, thank you @ankur-arch !
